- name: Install core packages
  block:
    - name: Install general packages
      apt:
        pkg:
        - build-essential
        - software-properties-common
        - curl
        - git
        - libssl-dev
        state: present
    - name: Install python packages
      apt:
        pkg:
        - python3-pip
        - python3-dev
        - python3-virtualenv
  become: true
  tags: core

